site_name: Level-4 Semester-II

copyright: Copyright &#x1F12F; 2026 <a href=https://github.com/suhail-asarat>Mir Suhail Asarat</a>

nav:
  - Courses: index.md
  - CSE-420 Project/Thesis: cse-420.md
  - CSE-421 Seminar: cse-421.md
  - CCE-421 Cryptography and Network Security: cce-421.md
  - CCE-423 Wireless and Cellular Communication: cce-423.md
  - CIT-421 Computer Graphics and Image Processing: cit-421.md
  - CIT-422 Computer Graphics and Image Processing Sessional: cit-422.md
  - CIT-423 Machine Learning: cit-423.md

theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - c
    - c++
    - java
    - python
    - bash
    - json
    - md
    - yaml
  
  features:
    - content.footnote.tooltips
  
  icon:
    admonition:
      <type>: material/alert-circle

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.extra
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # - pymdownx.blocks.caption


extra_css:
  - css/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - js/copy-code.js
  # - js/katex.js
  - js/mathjax.js
  # - https://unpkg.com/katex@0/dist/katex.min.js
  # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js